### ISSUE TITLE
Decibel in AnalyzeAudio callback

### ISSUE THREAD

**Issue by 19BCS1114** [exzos28/react-native-audio-analyzer#2]
Can analyzeAudio return `decibels` along with amplitude per second or per millisecond as requested by user?

**Comment by exzos28** [comment]
Hello! I'll research that. I had some problems with that before. 
You're welcome to PR or suggestions.

**Comment by exzos28** [comment]
Hello! Sorry for a long answer.
I've made some research, and found out that you can get decibels from amplitude:

https://www.reddit.com/r/askmath/comments/18n5v9z/how_to_calculate_db_from_audio_signal_amplitude/
