### ISSUE TITLE
Would it be possible to set timeInSeconds = {0.5} ?

### ISSUE THREAD

**Issue by JohnnyBoySou** [exzos28/react-native-audio-analyzer#3]
I would like to define timeInSeconds it as a prop or send it when analyze is called example: 

const data = await analyzeAudio(uri, 0.5);

**Comment by exzos28** [comment]
Hi, I'll find out and make PR as soon as possible.

**Comment by exzos28** [comment]
I've made changes and released new version 1.2.0
There you can find the second value groupBySeconds and more scale helpers.
Have a look
