### ISSUE TITLE
Can this library be used as a slider to scrub through the audio waves.

### ISSUE THREAD

**Issue by Gautham495** [exzos28/react-native-audio-analyzer#5]
Awesome work on making this library.

Do let me know if we can use this library to scrub through the audio waves to be used as a slider like how instagram does. Do let me know.

**Comment by exzos28** [comment]
Hello! The library only analyzes the audio files and provides audio data. Creating waveforms (UI) on your side. 

You can use this video as an example https://youtu.be/KrsBXKr6gdg?si=ENNMinnVs_hPO2mN

**Comment by Gautham495** [comment]
I was able to do it.

Please add it in your readme so you can show that this library works.

Here is the demo video:

https://x.com/gautham_vijay_/status/1835377883503591493

Thanks for making this library and fulfilling my wish of making a instagram style voice message scrubber after almost 2+ years of me trying to do it.

**Comment by exzos28** [comment]
The library does only one thing, and that is to provide audio data.
Based on them, a developer can easily draw an audio wave and bind it to a player (which can be anything, by the way), or use it for other purposes.

**Comment by Gautham495** [comment]
Yes. Thanks for making this library. Open source guys are a god send!
